# Generated by Django 4.2.11 on 2024-04-05 16:00

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_matricnumber_paid_fees_matricnumber_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricnumber',
            name='matric_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=9, max_length=7, prefix='IIC', unique=True),
        ),
    ]
